version: "3.9"

services:
  server:
    image:  'nginx:stable-alpine'
    ports:
     - '80:80'
    volumes:
      - /Users/postmind/code:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - {WEB_SRC}:/var/www/html:delegated
     - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
     - variables.env
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   env_file:
    - ./env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
    - ./env/phpmyadmin.env
    ports:
      - 81:80
